# Generated by Django 5.1.1 on 2024-09-26 14:22

import account.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, default=account.models.generate_token_field, editable=False, max_length=120, unique=True)),
                ('status', models.IntegerField(choices=[(-1, 'deactivate'), (1, 'activate'), (2, 'completed'), (3, 'expired')], db_index=True, default=1)),
                ('method', models.IntegerField(choices=[(0, 'not_set'), (1, 'email'), (2, 'phone_number')], db_index=True, default=0)),
                ('send_method', models.IntegerField(choices=[(1, 'email'), (2, 'sms')], db_index=True, default=1)),
                ('datetime_create', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('datetime_expire', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
